getwd()
elec_gen = read.csv(".\\Data\\electricity_generation_per_person.csv", header = TRUE, sep = ",")
View(elec_gen)
names(elec_gen)
names(elec_gen)[2:33] = substr(names(elec_gen)[2:33], 2, nchar(names(elec_gen)[2:33]))
#names(elec_gen) = substr(names(elec_gen), 2, nchar(names(elec_gen)))
names(elec_gen)

elec_use = read.csv(".\\Data\\electricity_use_per_person.csv", header = TRUE, sep = ",")
names(elec_use)
names(elec_use)[2:56] = substr(names(elec_use)[2:56], 2, nchar(names(elec_use)[2:56]))
names(elec_use)
View(elec_use)

#install.packages("tidyverse")
library(tidyr)
elec_gen_df = gather(elec_gen, -country, key = "year", value = "ElectricityGeneration")
elec_use_df = gather(elec_use, -country, key  = "year", value = "ElectricityUse")
elec_gen_use = merge(elec_gen_df, elec_use_df)
View(elec_gen_use)


total_15_24 = read.csv(".\\Data\\literacy_rate_youth_total_percent_of_people_ages_15_24.csv", header = TRUE, sep = ",")
male_15_24 = read.csv(".\\Data\\literacy_rate_youth_male_percent_of_males_ages_15_24.csv", header = TRUE, sep = ",")
female_15_24 = read.csv(".\\Data\\literacy_rate_youth_female_percent_of_females_ages_15_24.csv", header = TRUE, sep = ",")
total_15_above = read.csv(".\\Data\\literacy_rate_adult_total_percent_of_people_ages_15_and_above.csv", header = TRUE, sep = ",")
male_15_above = read.csv(".\\Data\\literacy_rate_adult_male_percent_of_males_ages_15_and_above.csv", header = TRUE, sep = ",")
female_15_above = read.csv(".\\Data\\literacy_rate_adult_female_percent_of_females_ages_15_above.csv", header = TRUE, sep = ",")
#names(total_15_24)
#View(total_15_24)


female_15_24_df = gather(female_15_24, -country, key = "year", value = "adult_female")
male_15_24_df = gather(male_15_24, -country, key = "year", value = "adult_male")
total_15_24_df = gather(total_15_24, -country, key = "year", value = "adult_total")
female_15_above_df = gather(female_15_above, -country, key = "year", value = "youth_female")
male_15_above_df = gather(male_15_above, -country, key = "year", value = "youth_male")
total_15_above_df = gather(total_15_above, -country, key = "year", value = "youth_total")

merge_rate1 = merge(female_15_24_df, male_15_24_df)
merge_rate2 = merge(total_15_24_df,female_15_above_df)
merge_rate3 = merge(male_15_above_df,total_15_above_df)
merge_rate4 = merge(merge_rate1, merge_rate2)
merge_rate5 = merge(merge_rate4, merge_rate3)
#View(merge_rate5)
merge_rate <- na.omit(merge_rate5)
View(merge_rate)

